version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      # target: production
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network
networks:
  app-network:
