version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run dev
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - DEBUG=nextjs:*
    env_file:
      - .env.local
