import { LoginPage } from '@/components/pages/auth/login';
import { Toaster } from '@/components/ui/sonner';

import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Authentification",
  description: "Generated by create next app",
};

export default function Login() {
  return (
    <>
      <div className="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">
      <Toaster position="top-center" richColors/>
      <div className="sm:mx-auto sm:w-full sm:max-w-sm">
        <h2 className="mt-10 text-center text-2xl/9 font-bold tracking-tight text-gray-900 dark:text-gray-100">Login page</h2>
      </div>
      <div className="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
        <LoginPage/>
      </div>
    </div>
    </>
  )
}
